### ISSUE TITLE
 Error: Command failed: adb  devices

### ISSUE THREAD

**Issue by Fengmaybe** [huruji/find-beauty-in-douyin#1]
环境：window10 + Android
运行：npm run start
报错，错误信息如下：
`E:\workspace.lvya\data_testPro_ly\find-beauty-in-douyin-master>npm run start

find-beauty-in-douyin@1.0.0 start E:\workspace.lvya\data_testPro_ly\find-beauty-in-douyin-master
node index.js

(node:7700) UnhandledPromiseRejectionWarning: Error: Error: Command failed: adb  devices

    at exec (E:\workspace.lvya\data_testPro_ly\find-beauty-in-douyin-master\adb.js:14:23)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:7700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

在其他任意位置上执行adb devices,会出现设备信息，如下：
`C:\Users\ya.lv>adb devices  

List of devices attached  

9e57e247        device`
thanks.

**Comment by Fengmaybe** [comment]
(node:9656) UnhandledPromiseRejectionWarning: Error: Error: Command failed: adb  devices

    at exec (F:\AI_Nodejs\find-beauty-in-douyin-master\adb.js:17:23)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:9656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by huruji** [comment]
目前可能需要您自己排查下，因为目前我身边没有 windows 环境
